version: '3.7'
services:
    postgres:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: opendatabs/docker-airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__WEBSERVER__RBAC=true
            - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.deny_all
            - AIRFLOW__WEBSERVER__BASE_URL=http://pvpdstata01:8080
            - AIRFLOW__WEBSERVER__AUTHENTICATE=True
            - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.password_auth
            - AIRFLOW__CLI__ENDPOINT_URL=http://pvpdstata01:8080
            - AIRFLOW__SMTP__SMTP_HOST=mail.bs.ch
            - AIRFLOW__SMTP__SMTP_MAIL_FROM=airflow@bs.ch
            - AIRFLOW__SMTP__SMTP_STARTTLS=False

        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags    
            - /var/run/docker.sock:/var/run/docker.sock:ro                    
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
